name: AbroadNews

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      # v4 ki jagah full SHA ID
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Set up Python
      # v5 ki jagah full SHA ID
      uses: actions/setup-python@82c352c9ed353590137459a2aa6741193d483c9d 
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install requests google-generativeai

    - name: Run News Script
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python update_news.py

    - name: Commit and Push Everything
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html news-sitemap.xml
        git commit -m "Latest AI News Updated: $(date)" || echo "No changes to commit"
        git push origin main
        
